const titulos = 
[
"Cómo sobrevivir a un apocalipsis zombie",
"Cómo hacer amigos y fingir que eres normal",
"Cómo no morir de aburrimiento",
"Guía para ser un ninja en el mundo laboral",
"Manual de supervivencia para suegras tóxicas",
"El arte de dormir en reuniones aburridas",
"Cómo ser feliz sin esforzarte",
"1001 excusas para no hacer ejercicio",
"Cómo fingir que sabes de vinos",
"El gran libro de las excusas para llegar tarde",
"Cómo dejar de procrastinar... mañana",
"La ciencia de hacer nada",
"Cómo ser perezoso y no morir en el intento",
"La guía completa para parecer inteligente sin serlo",
"El manual definitivo para ser un experto en perder el tiempo",
"Cómo engañar a tu jefe y no perder el empleo",
"Guía para ligar con extraterrestres",
"Cómo hacerse el interesante y fracasar en el intento",
"La biblia del tonto útil",
"Cómo hacer que tus amigos piensen que tienes vida social",
"Cómo dominar el arte de fingir interés",
"Manual para evitar el trabajo en equipo",
"Guía para hablar en público sin decir nada",
"Cómo mentir con estadísticas y no ser descubierto",
"Cómo ser un influencer sin talento",
"El arte de fingir que sabes de política",
"Cómo ser feliz sin dinero ni amigos",
"Cómo ligar en una biblioteca sin molestar a nadie",
"El gran libro de las excusas para no pagar la cuenta",
"Cómo triunfar en la vida sin esforzarte demasiado",
"Cómo parecer ocupado sin hacer nada",
"Cómo evitar el contacto visual y no parecer maleducado",
"Guía para fingir que sabes de arte moderno",
"Cómo hablar en público sin sudar en exceso",
"La guía del experto en pedir prestado y no devolver",
"Cómo ser un héroe sin hacer nada",
"Manual de supervivencia para viajar con la suegra",
"El arte de llegar tarde con estilo",
"Cómo ganar una discusión sin tener razón",
"Cómo hacer amigos sin esforzarte demasiado",
"La biblia del procrastinador profesional",
"Cómo parecer inteligente sin tener idea de nada",
"Guía para sobrevivir a una cena de Navidad con la familia política",
"Cómo ser un experto en fingir que trabajas",
"Cómo ser feliz sin hacer nada productivo",
"Cómo sobrevivir a una reunión de vecinos",
"Cómo fingir que tienes una vida social en las redes sociales",
"El gran libro de las excusas para no ir al gimnasio",
"Cómo ser un experto en no hacer nada útil",
"La guía para aparentar que sabes de música clásica",
"Cómo hablar por teléfono sin decir nada interesante",
"Cómo parecer un experto en cualquier tema sin tener idea",
"La biblia del perezoso exitoso",
"Cómo evitar el contacto con desconocidos sin parecer antisocial",
"Cómo hacer amigos en un bar sin gastar mucho dinero",
"Cómo fingir que lees sin abrir un libro",
"La guía del experto en perder el tiempo sin remordimientos",
"Cómo triunfar en la vida sin esforzarte ni un poco",
"Cómo ser el rey del sarcasmo y no ser odiado por todos",
"Cómo sobrevivir a un día sin Internet",
"Cómo parecer un experto en cualquier deporte sin haberlo practicado nunca",
"La biblia del vagabundo exitoso",
"Cómo evitar el trabajo duro sin ser despedido",
"Cómo hablar en público sin sudar en exceso",
"La guía del experto en pedir prestado y no devolver",
"Cómo ser un héroe sin hacer nada",
"Manual de supervivencia para viajar con la suegra",
"El arte de llegar tarde con estilo",
"Cómo ganar una discusión sin tener razón",
"Cómo hacer amigos sin esforzarte demasiado",
"La biblia del procrastinador profesional",
"Cómo parecer inteligente sin tener idea de nada",
"Guía para sobrevivir a una cena de Navidad con la familia política",
"Cómo ser un experto en fingir que trabajas",
"Cómo ser feliz sin hacer nada productivo",
"Cómo sobrevivir a una reunión de vecinos",
"Cómo fingir que tienes una vida social en las redes sociales",
"El gran libro de las excusas para no ir al gimnasio",
"Cómo ser un experto en no hacer nada útil",
"La guía para aparentar que sabes de música clásica",
"Cómo hablar por teléfono sin decir nada interesante",
"Cómo parecer un experto en cualquier tema sin tener idea",
"La biblia del perezoso exitoso",
"Cómo evitar el contacto con desconocidos sin parecer antisocial",
"Cómo hacer amigos en un bar sin gastar mucho dinero",
"Cómo fingir que lees sin abrir un libro",
"La guía del experto en perder el tiempo sin remordimientos",
"Cómo triunfar en la vida sin esforzarte ni un poco",
"Cómo ser el rey del sarcasmo y no ser odiado por todos",
"Cómo sobrevivir a un día sin Internet",
"Cómo parecer un experto en cualquier deporte sin haberlo practicado nunca",
"La biblia del vagabundo exitoso",
"Cómo evitar el trabajo duro sin ser despedido",
"Cómo ser un experto en fingir que eres productivo",
"Cómo hacer amigos en el trabajo sin caer en la tentación de hablar de él",
"Cómo sobrevivir a una cena de empresa sin arruinar tu reputación",
"Cómo ser un experto en fingir que eres un gurú de la tecnología",
"Cómo parecer interesante en una primera cita sin revelar demasiado",
"La guía para ser un vago productivo",
"Cómo evitar las reuniones de trabajo sin parecer irresponsable",
"Cómo triunfar en las redes sociales sin publicar nada interesante",
"El gran libro de las excusas para no hacer deporte",
"Cómo sobrevivir a una cena con veganos siendo carnívoro",
"La biblia del experto en evitar responsabilidades",
"Cómo fingir que eres un experto en vinos sin saber nada de ellos",
"Cómo ser un experto en parecer ocupado sin hacer nada",
"Guía para sobrevivir a una boda sin gastar demasiado dinero",
"Cómo evitar las tareas domésticas sin que tu pareja se dé cuenta",
"Cómo ser el rey de las fiestas sin gastar demasiado dinero",
"Cómo sobrevivir a una mudanza sin perder la cordura",
"Cómo hacer amigos en el gimnasio sin sudar demasiado",
"La guía del experto en fingir que tienes estilo",
"Cómo triunfar en una entrevista de trabajo sin saber nada del puesto",
"Cómo ser el mejor en fingir que trabajas desde casa",
"Cómo evitar las llamadas de teléfono sin parecer maleducado",
"La biblia del experto en fingir que entiendes la política",
"Cómo ser un experto en fingir que eres un gourmet sin gastar demasiado",
"Cómo triunfar en una cita a ciegas sin tener nada en común",
"Cómo hacer amigos en la cola del supermercado sin parecer desesperado",
"Cómo sobrevivir a una cena de Acción de Gracias sin pelear con la familia",
"Cómo parecer un experto en cualquier tema de conversación sin tener idea",
"Cómo ser un experto en fingir que eres culto sin leer un libro",
"Cómo fingir que eres un maestro del bricolaje sin romper nada",
"La guía del experto en llegar tarde sin parecer un irresponsable",
"Cómo ser un experto en ligar en línea sin tener fotos interesantes",
"Cómo triunfar en una cena de negocios sin hablar del trabajo",
"Cómo evitar a los compañeros de trabajo sin parecer antipático",
"La biblia del experto en fingir que estás interesado en una conversación aburrida",
"Cómo sobrevivir a un día sin internet sin aburrirte",
"Cómo ser un experto en fingir que tienes dinero sin gastar nada",
"Cómo triunfar en una presentación sin preparación",
"Cómo parecer un experto en cualquier idioma sin saber nada de él",
"La guía del experto en fingir que estás ocupado en el trabajo sin hacer nada",
"Cómo hacer amigos en la sala de espera del médico sin parecer extraño",
"Cómo sobrevivir a una fiesta de disfraces sin gastar demasiado dinero",
"Cómo ser el mejor en fingir que te gusta el deporte sin entender nada",
"Cómo parecer un experto en tecnología sin saber nada",
"Cómo triunfar en una cena romántica sin gastar demasiado dinero",
"La biblia del experto en fingir que sabes cocinar sin hacer nada",
"Cómo ser un experto en fingir que eres un viajero experimentado sin salir de casa",
"Cómo sobrevivir a una reunión de exalumnos sin sentirte viejo",
"Cómo hacer amigos en el transporte público sin parecer acosador",
"Cómo triunfar en una entrevista de trabajo sin haber dormido",
"Cómo ser un experto en fingir que eres un artista sin saber dibujar",
"La guía del experto en fingir que eres una persona madura sin dejar de ser un niño",
"Cómo sobrevivir a una cena navideña con la familia política sin pelear",
"Cómo parecer un experto en cine sin ver una sola película",
"Cómo ser un experto en fingir que eres un amante de los animales sin tener una mascota",
"Cómo ser un experto en fingir que eres un chef sin saber cocinar",
"La guía del experto en fingir que entiendes de vinos sin probarlos",
"Cómo triunfar en una cita a ciegas sin saber nada del otro",
"Cómo ser un experto en fingir que eres un escritor sin haber escrito nada",
"La biblia del experto en fingir que estás ocupado en tu tiempo libre sin hacer nada",
"Cómo hacer amigos en una fiesta sin parecer un desesperado",
"Cómo sobrevivir a un día de lluvia sin aburrirte",
"Cómo ser un experto en fingir que eres un deportista sin hacer ejercicio",
"Cómo triunfar en una fiesta de cumpleaños sin ser el protagonista",
"Cómo parecer un experto en política sin entender nada",
"La guía del experto en fingir que eres un músico sin saber tocar ningún instrumento",
"Cómo sobrevivir a una clase aburrida sin dormirte",
"Cómo ser un experto en fingir que eres un experto en cualquier cosa sin saber nada",
"Cómo triunfar en una cena en casa de amigos sin llevar nada de comer",
"Cómo hacer amigos en una conferencia sin parecer un nerd",
"Cómo parecer un experto en moda sin tener estilo",
"Cómo ser un experto en fingir que te gusta el arte sin entender nada",
"La biblia del experto en fingir que eres un geek sin saber de tecnología",
"Cómo sobrevivir a una entrevista de trabajo sin sudar",
"Cómo ser un experto en fingir que eres un experto en psicología sin tener estudios",
"Cómo triunfar en una reunión de padres sin que te juzguen",
"Cómo parecer un experto en historia sin saber nada",
"Cómo hacer amigos en un bar sin gastar mucho dinero",
"Cómo ser un experto en fingir que eres un poeta sin haber escrito ningún poema",
]
const frases = 
[
  "Conviértete en un maestro de la improvisación en cualquier situación social y aprende a salir airoso de cualquier conversación, incluso si no tienes ni idea de lo que están hablando tus interlocutores. Descubre cómo dominar la habilidad de hablar sin decir nada y cómo aparentar interés en temas que te aburren mortalmente.",
  "Descubre cómo parecer un experto en cualquier tema sin tener que saber realmente nada al respecto. Aprende los trucos para hablar con seguridad y autoridad, cómo esquivar preguntas incómodas y cómo redirigir la conversación hacia temas que sí dominas.",
  "Aprende a sobrevivir a situaciones incómodas sin sudar la gota gorda. Descubre cómo lidiar con esos momentos en los que no sabes qué decir, cómo hacer para no quedar como un idiota y cómo mantener la calma cuando todo parece ir mal.",
  "Descubre cómo hacer amigos sin parecer un desesperado o un nerd. Aprende las técnicas más efectivas para conectar con la gente, cómo iniciar y mantener una conversación interesante y cómo caer bien a todo el mundo sin necesidad de ser falso.",
  "Conviértete en un experto en fingir que te gusta algo sin tener que saber realmente nada al respecto. Descubre cómo hacer creer a los demás que eres un apasionado de la música clásica, el arte abstracto o cualquier otro tema que te parezca aburrido. Aprende a emitir comentarios ingeniosos y cómo dar la impresión de que tienes un gusto refinado y exquisito.",
  "Aprende a triunfar en situaciones cotidianas sin tener que hacer mucho esfuerzo. Descubre cómo aprovechar al máximo cada oportunidad para brillar y cómo hacer que los demás se fijen en ti sin necesidad de hacer nada espectacular. Aprende a destacar en cualquier situación, ya sea en una cena familiar, en una reunión de trabajo o en una cita romántica.",
  "Descubre cómo impresionar a tus amigos con habilidades que no posees sin que se den cuenta. Aprende a hacer trucos de magia, a tocar un instrumento o a bailar salsa sin tener que pasar horas y horas practicando. Descubre los secretos para hacer que parezca que llevas toda la vida dedicado a esa actividad.",
  "Conviértete en un experto en fingir que tienes experiencia en cualquier ámbito laboral sin tener que haber trabajado nunca. Descubre cómo redactar un currículum que te haga parecer un profesional experimentado, cómo prepararte para una entrevista de trabajo y cómo hacer que tu potencial empleador te contrate sin saber que eres un novato total.",
];
//
const generarTitulo = () => titulos[Math.floor(Math.random() * titulos.length)];
const generarFrase = () => frases[Math.floor(Math.random() * frases.length)];
//
chrome.browserAction.onClicked.addListener(tab => chrome.tabs.create({ 'url': chrome.extension.getURL('popup.html') }));
//
document.addEventListener("DOMContentLoaded", event =>
{
  document.getElementById("title-frase").textContent = generarTitulo();
  document.getElementById("frase").textContent = generarFrase();
});
